---
- name:
  postgresql_privs:
    database: "{{ item.database }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(postgresql_port) }}"
    objs: "{{ item.objs | default('ALL_IN_SCHEMA') }}"
    state: "{{ item.state | default('present') }}"
    privs: "{{ item.privs | default('ALL') }}"
    type: "{{ item.type | default(omit) }}"
    roles: "{{ item.roles }}"
    target_roles: "{{ item.target_roles | default(omit) }}"
  with_items: "{{ postgresql_privileges }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true