---
dependencies: []

galaxy_info:
  role_name: postgresql
  author: geerlingguy
  description: PostgreSQL server for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - database
    - postgresql
    - postgres
    - rdbms
