---
__postgresql_version: "12.2"
__postgresql_data_dir: "/var/lib/pgsql/data"
__postgresql_bin_path: "/usr/bin"
__postgresql_config_path: "/var/lib/pgsql/data"
__postgresql_daemon: postgresql
__postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib
  - postgresql-libs
__postgresql_unix_socket_directories_mode: '0755'
# Fedora 32 containers only have python3 by default
postgresql_python_library: python3-psycopg2
